[package]
name = "fabricator-compiler"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arrayvec.workspace = true
either.workspace = true
gc-arena.workspace = true
rustc-hash.workspace = true
serde.workspace = true
thiserror.workspace = true

fabricator-vm.workspace = true
fabricator-util.workspace = true
